#Requires -RunAsAdministrator
<#
.SYNOPSIS
    OpenVox Agent Bootstrap Script for Windows

.DESCRIPTION
    This script is dynamically generated by OpenVox WebUI and:
      - Downloads the latest OpenVox Agent MSI from the official repository
      - Installs the agent silently via msiexec
      - Configures puppet.conf to point to the Puppet server
      - Starts the Puppet agent service
      - Runs the initial Puppet agent for certificate signing request

    Supported Operating Systems:
      - Windows Server 2016, 2019, 2022, 2025
      - Windows 10, 11

.PARAMETER NonInteractive
    Skip confirmation prompts for automated deployments.

.PARAMETER DryRun
    Show what the script would do without making changes.

.EXAMPLE
    # Download and run via PowerShell:
    iex (iwr 'https://your-openvox-webui/api/v1/bootstrap/windows-script').Content

    # Non-interactive:
    $script = (iwr 'https://your-openvox-webui/api/v1/bootstrap/windows-script').Content
    & ([scriptblock]::Create($script)) -NonInteractive

    # Dry run:
    $script = (iwr 'https://your-openvox-webui/api/v1/bootstrap/windows-script').Content
    & ([scriptblock]::Create($script)) -DryRun

.NOTES
    Generated by OpenVox WebUI - https://github.com/ffquintella/openvox-webui
#>

param(
    [switch]$NonInteractive,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

# Configuration (injected by OpenVox WebUI)
$OPENVOX_SERVER = "{{OPENVOX_SERVER}}"
$PACKAGE_NAME = "{{PACKAGE_NAME}}"

# Download repository
$DOWNLOAD_BASE_URL = "https://downloads.voxpupuli.org/windows/openvox8"

# Paths
$PUPPET_INSTALL_DIR = "C:\Program Files\Puppet Labs\Puppet"
$PUPPET_CONF_DIR = "$PUPPET_INSTALL_DIR\puppet\etc"
$PUPPET_BIN = "$PUPPET_INSTALL_DIR\bin\puppet.bat"

# ============================================================================
# Helper functions
# ============================================================================

function Write-Banner {
    Write-Host ""
    Write-Host "============================================================" -ForegroundColor Cyan
    Write-Host "  OpenVox Agent Bootstrap for Windows" -ForegroundColor Cyan
    Write-Host "============================================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  Puppet Server : $OPENVOX_SERVER" -ForegroundColor White
    Write-Host "  Package       : $PACKAGE_NAME" -ForegroundColor White
    Write-Host "  Download URL  : $DOWNLOAD_BASE_URL" -ForegroundColor White
    if ($DryRun) {
        Write-Host "  Mode          : DRY RUN (no changes will be made)" -ForegroundColor Yellow
    }
    Write-Host ""
}

function Write-Step {
    param([string]$Message)
    Write-Host "[*] $Message" -ForegroundColor Green
}

function Write-Info {
    param([string]$Message)
    Write-Host "    $Message" -ForegroundColor Gray
}

function Write-Warn {
    param([string]$Message)
    Write-Host "[!] $Message" -ForegroundColor Yellow
}

function Write-Err {
    param([string]$Message)
    Write-Host "[ERROR] $Message" -ForegroundColor Red
}

function Test-Administrator {
    $currentPrincipal = New-Object Security.Principal.WindowsPrincipal(
        [Security.Principal.WindowsIdentity]::GetCurrent()
    )
    return $currentPrincipal.IsInRole(
        [Security.Principal.WindowsBuiltInRole]::Administrator
    )
}

# ============================================================================
# Find latest MSI version from download repository
# ============================================================================

function Get-LatestMsiUrl {
    Write-Step "Discovering latest OpenVox Agent version..."

    try {
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

        $page = Invoke-WebRequest -Uri "$DOWNLOAD_BASE_URL/" -UseBasicParsing
        $links = $page.Links | Where-Object { $_.href -match "openvox-agent-.*-x64\.msi$" }

        if (-not $links -or $links.Count -eq 0) {
            Write-Err "No MSI packages found at $DOWNLOAD_BASE_URL/"
            throw "No packages found"
        }

        # Extract version numbers and sort to find latest
        $versions = @()
        foreach ($link in $links) {
            $href = $link.href
            if ($href -match "openvox-agent-([\d]+\.[\d]+\.[\d]+(?:-[a-zA-Z0-9]+)?)-x64\.msi") {
                $versionStr = $Matches[1]
                # Skip release candidates
                if ($versionStr -match "-rc") { continue }
                $versions += [PSCustomObject]@{
                    Version    = $versionStr
                    SortKey    = [Version]($versionStr -replace "-.*$", "")
                    Filename   = "openvox-agent-$versionStr-x64.msi"
                    Url        = "$DOWNLOAD_BASE_URL/openvox-agent-$versionStr-x64.msi"
                }
            }
        }

        if ($versions.Count -eq 0) {
            Write-Err "Could not parse any stable versions from download page"
            throw "No stable versions found"
        }

        $latest = $versions | Sort-Object -Property SortKey -Descending | Select-Object -First 1
        Write-Info "Latest version: $($latest.Version)"
        Write-Info "Download URL: $($latest.Url)"

        return $latest
    }
    catch {
        Write-Err "Failed to discover latest version: $_"
        throw
    }
}

# ============================================================================
# Download MSI
# ============================================================================

function Get-MsiInstaller {
    param([PSCustomObject]$VersionInfo)

    $tempDir = Join-Path $env:TEMP "openvox-bootstrap"
    if (-not (Test-Path $tempDir)) {
        New-Item -ItemType Directory -Path $tempDir -Force | Out-Null
    }

    $msiPath = Join-Path $tempDir $VersionInfo.Filename

    if (Test-Path $msiPath) {
        Write-Info "MSI already downloaded: $msiPath"
        return $msiPath
    }

    Write-Step "Downloading $($VersionInfo.Filename)..."

    if ($DryRun) {
        Write-Info "[DRY RUN] Would download from: $($VersionInfo.Url)"
        Write-Info "[DRY RUN] Would save to: $msiPath"
        return $msiPath
    }

    try {
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $VersionInfo.Url -OutFile $msiPath -UseBasicParsing
        Write-Info "Downloaded to: $msiPath"
        return $msiPath
    }
    catch {
        Write-Err "Failed to download MSI: $_"
        throw
    }
}

# ============================================================================
# Install MSI
# ============================================================================

function Install-OpenvoxAgent {
    param([string]$MsiPath)

    Write-Step "Installing OpenVox Agent..."

    $msiArgs = @(
        "/i", "`"$MsiPath`"",
        "/qn",
        "/norestart",
        "PUPPET_AGENT_STARTUP_MODE=Automatic",
        "PUPPET_SERVER=$OPENVOX_SERVER"
    )

    Write-Info "Running: msiexec.exe $($msiArgs -join ' ')"

    if ($DryRun) {
        Write-Info "[DRY RUN] Would run msiexec with above arguments"
        return
    }

    $process = Start-Process -FilePath "msiexec.exe" -ArgumentList $msiArgs -Wait -PassThru -NoNewWindow
    if ($process.ExitCode -ne 0) {
        Write-Err "msiexec failed with exit code: $($process.ExitCode)"
        throw "Installation failed"
    }

    Write-Info "Installation completed successfully"
}

# ============================================================================
# Configure puppet.conf
# ============================================================================

function Set-PuppetConfig {
    Write-Step "Configuring puppet.conf..."

    $confFile = Join-Path $PUPPET_CONF_DIR "puppet.conf"

    if ($DryRun) {
        Write-Info "[DRY RUN] Would write puppet.conf to: $confFile"
        Write-Info "[DRY RUN] server = $OPENVOX_SERVER"
        return
    }

    # Ensure config directory exists
    if (-not (Test-Path $PUPPET_CONF_DIR)) {
        New-Item -ItemType Directory -Path $PUPPET_CONF_DIR -Force | Out-Null
    }

    $confContent = @"
[main]
server = $OPENVOX_SERVER
"@

    if (Test-Path $confFile) {
        # Check if server is already configured
        $existing = Get-Content $confFile -Raw
        if ($existing -match "server\s*=") {
            Write-Info "puppet.conf already has a server setting, updating..."
            $confContent = $existing -replace "server\s*=\s*.*", "server = $OPENVOX_SERVER"
        }
        else {
            # Append to [main] section
            $confContent = $existing.TrimEnd() + "`nserver = $OPENVOX_SERVER`n"
        }
    }

    Set-Content -Path $confFile -Value $confContent -Encoding UTF8
    Write-Info "puppet.conf configured at: $confFile"
}

# ============================================================================
# Start Puppet service and initial run
# ============================================================================

function Start-PuppetService {
    Write-Step "Starting Puppet agent service..."

    if ($DryRun) {
        Write-Info "[DRY RUN] Would start and enable the puppet service"
        return
    }

    $service = Get-Service -Name "puppet" -ErrorAction SilentlyContinue
    if (-not $service) {
        Write-Warn "Puppet service not found. It may be registered with a different name."
        Write-Info "Checking for available puppet services..."
        Get-Service | Where-Object { $_.Name -like "*puppet*" } | ForEach-Object {
            Write-Info "  Found: $($_.Name) - $($_.Status)"
        }
        return
    }

    Set-Service -Name "puppet" -StartupType Automatic
    Start-Service -Name "puppet"
    Write-Info "Puppet service started and set to automatic"
}

function Invoke-InitialPuppetRun {
    Write-Step "Running initial Puppet agent (certificate signing request)..."

    if ($DryRun) {
        Write-Info "[DRY RUN] Would run: puppet agent --test --waitforcert 0"
        return
    }

    if (-not (Test-Path $PUPPET_BIN)) {
        # Try common alternative paths
        $altPaths = @(
            "C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat",
            "C:\Program Files\Puppet Labs\Puppet\puppet\bin\puppet.bat"
        )
        $found = $false
        foreach ($altPath in $altPaths) {
            if (Test-Path $altPath) {
                $script:PUPPET_BIN = $altPath
                $found = $true
                break
            }
        }
        if (-not $found) {
            Write-Warn "puppet.bat not found at expected paths"
            Write-Info "You may need to run the initial puppet agent manually after installation completes"
            return
        }
    }

    Write-Info "Running: $PUPPET_BIN agent --test --waitforcert 0"
    try {
        & $PUPPET_BIN agent --test --waitforcert 0
    }
    catch {
        # Exit code 1 is normal for first run (changes applied)
        Write-Info "Initial Puppet run completed (certificate request submitted)"
    }
}

# ============================================================================
# Main
# ============================================================================

function Main {
    Write-Banner

    # Validate configuration
    if ([string]::IsNullOrWhiteSpace($OPENVOX_SERVER) -or $OPENVOX_SERVER -eq "{{OPENVOX_SERVER}}") {
        Write-Err "OpenVox Server URL is not configured!"
        Write-Err "Please configure 'openvox_server_url' in your OpenVox WebUI settings."
        exit 1
    }

    # Confirm with user unless non-interactive
    if (-not $NonInteractive -and -not $DryRun) {
        Write-Host ""
        Write-Host "This script will:" -ForegroundColor White
        Write-Host "  1. Download the latest OpenVox Agent MSI" -ForegroundColor White
        Write-Host "  2. Install the agent silently" -ForegroundColor White
        Write-Host "  3. Configure puppet.conf with server: $OPENVOX_SERVER" -ForegroundColor White
        Write-Host "  4. Start the Puppet agent service" -ForegroundColor White
        Write-Host "  5. Submit a certificate signing request" -ForegroundColor White
        Write-Host ""
        $confirm = Read-Host "Continue? [Y/n]"
        if ($confirm -and $confirm.ToLower() -ne "y") {
            Write-Host "Aborted." -ForegroundColor Yellow
            exit 0
        }
    }

    # Execute steps
    $versionInfo = Get-LatestMsiUrl
    $msiPath = Get-MsiInstaller -VersionInfo $versionInfo
    Install-OpenvoxAgent -MsiPath $msiPath
    Set-PuppetConfig
    Start-PuppetService
    Invoke-InitialPuppetRun

    # Cleanup temp files
    if (-not $DryRun) {
        $tempDir = Join-Path $env:TEMP "openvox-bootstrap"
        if (Test-Path $tempDir) {
            Remove-Item -Path $tempDir -Recurse -Force -ErrorAction SilentlyContinue
        }
    }

    Write-Host ""
    Write-Host "============================================================" -ForegroundColor Green
    Write-Host "  Bootstrap Complete!" -ForegroundColor Green
    Write-Host "============================================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "  Next step: Sign the node's certificate in OpenVox WebUI" -ForegroundColor White
    Write-Host "  Navigate to: CA Management > Pending Requests" -ForegroundColor White
    Write-Host ""
}

# Run main
Main
