#Requires -RunAsAdministrator
<#
.SYNOPSIS
    OpenVox Agent Bootstrap Script for Windows

.DESCRIPTION
    This script is dynamically generated by OpenVox WebUI and:
      - Downloads the latest OpenVox Agent MSI from the official repository
      - Installs the agent silently via msiexec
      - Configures puppet.conf (server + runinterval) in the Windows confdir
      - Runs the initial Puppet agent for certificate signing request
      - Registers the Puppet agent service, sets it to start automatically,
        starts it, and verifies it reached the Running state so the node
        keeps checking in unattended

    Supported Operating Systems:
      - Windows Server 2016, 2019, 2022, 2025
      - Windows 10, 11

.PARAMETER NonInteractive
    Skip confirmation prompts for automated deployments.

.PARAMETER DryRun
    Show what the script would do without making changes.

.EXAMPLE
    # Download and run via PowerShell:
    iex (iwr 'https://your-openvox-webui/api/v1/bootstrap/windows-script').Content

    # Non-interactive:
    $script = (iwr 'https://your-openvox-webui/api/v1/bootstrap/windows-script').Content
    & ([scriptblock]::Create($script)) -NonInteractive

    # Dry run:
    $script = (iwr 'https://your-openvox-webui/api/v1/bootstrap/windows-script').Content
    & ([scriptblock]::Create($script)) -DryRun

.NOTES
    Generated by OpenVox WebUI - https://github.com/ffquintella/openvox-webui
#>

param(
    [switch]$NonInteractive,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

# Set when msiexec reports that a reboot is pending (exit code 3010/1641)
$RebootRequired = $false

# Configuration (injected by OpenVox WebUI)
$OPENVOX_SERVER = "{{OPENVOX_SERVER}}"
$PACKAGE_NAME = "{{PACKAGE_NAME}}"

# Download repository
$DOWNLOAD_BASE_URL = "https://downloads.voxpupuli.org/windows/openvox8"

# Paths
$PUPPET_INSTALL_DIR = "C:\Program Files\Puppet Labs\Puppet"
# On Windows the system-wide confdir lives under ProgramData, NOT under the
# install directory. Writing to "$PUPPET_INSTALL_DIR\puppet\etc" produces a
# puppet.conf that the agent never reads.
$PUPPET_CONF_DIR = Join-Path $env:ProgramData "PuppetLabs\puppet\etc"
$PUPPET_BIN = "$PUPPET_INSTALL_DIR\bin\puppet.bat"

# Windows service registered by the MSI ("Puppet Agent"). Discovery may update
# this if the package ever registers it under a different name.
$PUPPET_SERVICE_NAME = "puppet"

# How often the unattended agent applies the catalog
$PUPPET_RUNINTERVAL = "30m"

# ============================================================================
# Helper functions
# ============================================================================

function Write-Banner {
    Write-Host ""
    Write-Host "============================================================" -ForegroundColor Cyan
    Write-Host "  OpenVox Agent Bootstrap for Windows" -ForegroundColor Cyan
    Write-Host "============================================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  Puppet Server : $OPENVOX_SERVER" -ForegroundColor White
    Write-Host "  Package       : $PACKAGE_NAME" -ForegroundColor White
    Write-Host "  Download URL  : $DOWNLOAD_BASE_URL" -ForegroundColor White
    if ($DryRun) {
        Write-Host "  Mode          : DRY RUN (no changes will be made)" -ForegroundColor Yellow
    }
    Write-Host ""
}

function Write-Step {
    param([string]$Message)
    Write-Host "[*] $Message" -ForegroundColor Green
}

function Write-Info {
    param([string]$Message)
    Write-Host "    $Message" -ForegroundColor Gray
}

function Write-Warn {
    param([string]$Message)
    Write-Host "[!] $Message" -ForegroundColor Yellow
}

function Write-Err {
    param([string]$Message)
    Write-Host "[ERROR] $Message" -ForegroundColor Red
}

function Test-Administrator {
    $currentPrincipal = New-Object Security.Principal.WindowsPrincipal(
        [Security.Principal.WindowsIdentity]::GetCurrent()
    )
    return $currentPrincipal.IsInRole(
        [Security.Principal.WindowsBuiltInRole]::Administrator
    )
}

# ============================================================================
# Find latest MSI version from download repository
# ============================================================================

function Get-LatestMsiUrl {
    Write-Step "Discovering latest OpenVox Agent version..."

    try {
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

        $page = Invoke-WebRequest -Uri "$DOWNLOAD_BASE_URL/" -UseBasicParsing
        $links = $page.Links | Where-Object { $_.href -match "openvox-agent-.*-x64\.msi$" }

        if (-not $links -or $links.Count -eq 0) {
            Write-Err "No MSI packages found at $DOWNLOAD_BASE_URL/"
            throw "No packages found"
        }

        # Extract version numbers and sort to find latest
        $versions = @()
        foreach ($link in $links) {
            $href = $link.href
            if ($href -match "openvox-agent-([\d]+\.[\d]+\.[\d]+(?:-[a-zA-Z0-9]+)?)-x64\.msi") {
                $versionStr = $Matches[1]
                # Skip release candidates
                if ($versionStr -match "-rc") { continue }
                $versions += [PSCustomObject]@{
                    Version    = $versionStr
                    SortKey    = [Version]($versionStr -replace "-.*$", "")
                    Filename   = "openvox-agent-$versionStr-x64.msi"
                    Url        = "$DOWNLOAD_BASE_URL/openvox-agent-$versionStr-x64.msi"
                }
            }
        }

        if ($versions.Count -eq 0) {
            Write-Err "Could not parse any stable versions from download page"
            throw "No stable versions found"
        }

        $latest = $versions | Sort-Object -Property SortKey -Descending | Select-Object -First 1
        Write-Info "Latest version: $($latest.Version)"
        Write-Info "Download URL: $($latest.Url)"

        return $latest
    }
    catch {
        Write-Err "Failed to discover latest version: $_"
        throw
    }
}

# ============================================================================
# Download MSI
# ============================================================================

function Get-MsiInstaller {
    param([PSCustomObject]$VersionInfo)

    $tempDir = Join-Path $env:TEMP "openvox-bootstrap"
    if (-not (Test-Path $tempDir)) {
        New-Item -ItemType Directory -Path $tempDir -Force | Out-Null
    }

    $msiPath = Join-Path $tempDir $VersionInfo.Filename

    if (Test-Path $msiPath) {
        Write-Info "MSI already downloaded: $msiPath"
        return $msiPath
    }

    Write-Step "Downloading $($VersionInfo.Filename)..."

    if ($DryRun) {
        Write-Info "[DRY RUN] Would download from: $($VersionInfo.Url)"
        Write-Info "[DRY RUN] Would save to: $msiPath"
        return $msiPath
    }

    try {
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $VersionInfo.Url -OutFile $msiPath -UseBasicParsing
        Write-Info "Downloaded to: $msiPath"
        return $msiPath
    }
    catch {
        Write-Err "Failed to download MSI: $_"
        throw
    }
}

# ============================================================================
# Install MSI
# ============================================================================

function Install-OpenvoxAgent {
    param([string]$MsiPath)

    Write-Step "Installing OpenVox Agent..."

    $msiArgs = @(
        "/i", "`"$MsiPath`"",
        "/qn",
        "/norestart",
        "PUPPET_AGENT_STARTUP_MODE=Automatic",
        "PUPPET_SERVER=$OPENVOX_SERVER"
    )

    Write-Info "Running: msiexec.exe $($msiArgs -join ' ')"

    if ($DryRun) {
        Write-Info "[DRY RUN] Would run msiexec with above arguments"
        return
    }

    $process = Start-Process -FilePath "msiexec.exe" -ArgumentList $msiArgs -Wait -PassThru -NoNewWindow

    # 0 = success, 3010/1641 = success but a reboot is pending. Treating the
    # reboot codes as failures aborted the script before the service was ever
    # configured, leaving the agent installed but never running unattended.
    switch ($process.ExitCode) {
        0 { Write-Info "Installation completed successfully" }
        3010 {
            Write-Warn "Installation completed, but Windows reports a reboot is required"
            $script:RebootRequired = $true
        }
        1641 {
            Write-Warn "Installation completed and initiated a reboot"
            $script:RebootRequired = $true
        }
        default {
            Write-Err "msiexec failed with exit code: $($process.ExitCode)"
            throw "Installation failed"
        }
    }
}

# ============================================================================
# Service registration / startup configuration
# ============================================================================

function Test-PuppetServiceExists {
    param([string]$ServiceName = $PUPPET_SERVICE_NAME)

    # Get-Service is the existence check because it works even where the CIM
    # layer is restricted - a CIM failure must not be mistaken for a missing
    # service, which would trigger a pointless repair install.
    return [bool](Get-Service -Name $ServiceName -ErrorAction SilentlyContinue)
}

function Get-PuppetServiceInfo {
    # Win32_Service is only used for the extra detail Get-Service does not
    # expose consistently across Windows versions (StartMode, ExitCode).
    return Get-CimInstance -ClassName Win32_Service `
        -Filter "Name='$PUPPET_SERVICE_NAME'" -ErrorAction SilentlyContinue
}

function Get-PuppetServiceStartMode {
    param([string]$ServiceName = $PUPPET_SERVICE_NAME)

    $info = Get-CimInstance -ClassName Win32_Service `
        -Filter "Name='$ServiceName'" -ErrorAction SilentlyContinue
    if ($info) { return $info.StartMode }

    $svc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
    if ($svc -and $svc.PSObject.Properties.Name -contains "StartType") {
        return $svc.StartType
    }

    return "unknown"
}

function Find-PuppetService {
    if (Test-PuppetServiceExists) {
        return $PUPPET_SERVICE_NAME
    }

    # Fall back to discovery in case the package registers a different name.
    Write-Info "Service '$PUPPET_SERVICE_NAME' not found, searching for puppet services..."
    $candidates = Get-Service -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -like "*puppet*" -and $_.Name -ne "pxp-agent" }

    foreach ($candidate in $candidates) {
        Write-Info "  Found: $($candidate.Name) - $($candidate.Status)"
    }

    $match = $candidates | Select-Object -First 1
    if ($match) {
        $script:PUPPET_SERVICE_NAME = $match.Name
        Write-Info "Using service: $($match.Name)"
        return $match.Name
    }

    return $null
}

function Repair-PuppetServiceRegistration {
    param([string]$MsiPath)

    Write-Warn "Puppet agent service is not registered - repairing the installation..."

    if (-not (Test-Path $MsiPath)) {
        Write-Err "MSI no longer available at $MsiPath, cannot repair the installation"
        return $null
    }

    $msiArgs = @(
        "/i", "`"$MsiPath`"",
        "/qn",
        "/norestart",
        "REINSTALL=ALL",
        "REINSTALLMODE=amus",
        "PUPPET_AGENT_STARTUP_MODE=Automatic",
        "PUPPET_SERVER=$OPENVOX_SERVER"
    )

    Write-Info "Running: msiexec.exe $($msiArgs -join ' ')"
    $process = Start-Process -FilePath "msiexec.exe" -ArgumentList $msiArgs -Wait -PassThru -NoNewWindow
    if ($process.ExitCode -notin @(0, 1641, 3010)) {
        Write-Err "Repair install failed with exit code: $($process.ExitCode)"
        return $null
    }

    return Find-PuppetService
}

function Set-PuppetServiceAutomatic {
    param([string]$ServiceName)

    Write-Info "Setting '$ServiceName' startup type to Automatic..."

    # sc.exe first: it is the only reliable way to bring a Disabled service
    # back to Auto on every Windows version. Relax ErrorActionPreference so
    # stderr from the native command is not turned into a terminating error.
    $previousPreference = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        $scOutput = & sc.exe config $ServiceName start= auto
        $scExit = $LASTEXITCODE
    }
    finally {
        $ErrorActionPreference = $previousPreference
    }

    if ($scExit -ne 0) {
        Write-Warn "sc.exe config returned $scExit : $scOutput"
        try {
            Set-Service -Name $ServiceName -StartupType Automatic -ErrorAction Stop
        }
        catch {
            Write-Err "Could not set '$ServiceName' to start automatically: $_"
            return $false
        }
    }

    return $true
}

function Start-PuppetServiceAndWait {
    param(
        [string]$ServiceName,
        [int]$TimeoutSeconds = 60
    )

    Write-Info "Starting '$ServiceName'..."

    try {
        Start-Service -Name $ServiceName -ErrorAction Stop
    }
    catch {
        Write-Warn "Start-Service reported: $_"
    }

    # Start-Service can return before the service is actually running, so poll.
    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    while ((Get-Date) -lt $deadline) {
        $svc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
        if ($svc -and $svc.Status -eq "Running") {
            return $true
        }
        Start-Sleep -Seconds 2
    }

    return $false
}

function Stop-PuppetServiceIfRunning {
    param([string]$ServiceName)

    $svc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
    if ($svc -and $svc.Status -eq "Running") {
        Write-Info "Stopping '$ServiceName' so the initial foreground run can acquire the agent lock..."
        try {
            Stop-Service -Name $ServiceName -Force -ErrorAction Stop
            $svc.WaitForStatus("Stopped", [TimeSpan]::FromSeconds(60))
        }
        catch {
            Write-Warn "Could not stop '$ServiceName': $_"
        }
    }
}

# ============================================================================
# Configure puppet.conf
# ============================================================================

function Set-PuppetConfig {
    Write-Step "Configuring puppet.conf..."

    $confFile = Join-Path $PUPPET_CONF_DIR "puppet.conf"

    if ($DryRun) {
        Write-Info "[DRY RUN] Would write puppet.conf to: $confFile"
        Write-Info "[DRY RUN] server = $OPENVOX_SERVER"
        Write-Info "[DRY RUN] runinterval = $PUPPET_RUNINTERVAL"
        return
    }

    # Ensure config directory exists
    if (-not (Test-Path $PUPPET_CONF_DIR)) {
        New-Item -ItemType Directory -Path $PUPPET_CONF_DIR -Force | Out-Null
    }

    if (Test-Path $confFile) {
        $backup = "$confFile.backup.$(Get-Date -Format 'yyyyMMddHHmmss')"
        Copy-Item -Path $confFile -Destination $backup -Force
        Write-Info "Backed up existing puppet.conf to: $backup"
    }

    # Written wholesale (like the Linux bootstrap) so the unattended runinterval
    # is always present. The previous in-place edit rewrote every line matching
    # `server\s*=`, which also clobbered keys such as `ca_server`.
    $confContent = @"
[main]
server = $OPENVOX_SERVER

[agent]
# Run the puppet agent service every $PUPPET_RUNINTERVAL
runinterval = $PUPPET_RUNINTERVAL
"@

    Set-Content -Path $confFile -Value $confContent -Encoding UTF8
    Write-Info "puppet.conf configured at: $confFile"
    Write-Info "  server       = $OPENVOX_SERVER"
    Write-Info "  runinterval  = $PUPPET_RUNINTERVAL"
}

# ============================================================================
# Register / enable the Puppet agent service, and initial run
# ============================================================================

function Register-PuppetService {
    param([string]$MsiPath)

    Write-Step "Verifying the Puppet agent service is registered..."

    if ($DryRun) {
        Write-Info "[DRY RUN] Would verify the '$PUPPET_SERVICE_NAME' service exists"
        Write-Info "[DRY RUN] Would repair the MSI install if it is missing"
        return $true
    }

    $serviceName = Find-PuppetService
    if (-not $serviceName) {
        $serviceName = Repair-PuppetServiceRegistration -MsiPath $MsiPath
    }

    if (-not $serviceName) {
        Write-Err "The Puppet agent service could not be registered."
        Write-Err "The agent will NOT run unattended until the service exists."
        Write-Err "Reinstall the MSI manually with:"
        Write-Err "  msiexec /qn /norestart /i <openvox-agent.msi> PUPPET_AGENT_STARTUP_MODE=Automatic PUPPET_SERVER=$OPENVOX_SERVER"
        return $false
    }

    $svc = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
    $startMode = Get-PuppetServiceStartMode -ServiceName $serviceName
    Write-Info "Service '$serviceName' is registered (state: $($svc.Status), startup: $startMode)"
    return $true
}

function Enable-PuppetService {
    Write-Step "Enabling and starting the Puppet agent service..."

    if ($DryRun) {
        Write-Info "[DRY RUN] Would set '$PUPPET_SERVICE_NAME' to Automatic and start it"
        return $true
    }

    if (-not (Test-PuppetServiceExists)) {
        Write-Warn "Service '$PUPPET_SERVICE_NAME' is not present, skipping enable"
        return $false
    }

    # Always (re)assert Automatic: an upgrade over an existing install does not
    # reset a service left on Manual or Disabled, which is what kept the agent
    # from running unattended.
    if (-not (Set-PuppetServiceAutomatic -ServiceName $PUPPET_SERVICE_NAME)) {
        return $false
    }

    if (-not (Start-PuppetServiceAndWait -ServiceName $PUPPET_SERVICE_NAME)) {
        Write-Err "Service '$PUPPET_SERVICE_NAME' did not reach the Running state"
        $info = Get-PuppetServiceInfo
        if ($info) {
            Write-Err "  State     : $($info.State)"
            Write-Err "  StartMode : $($info.StartMode)"
            Write-Err "  ExitCode  : $($info.ExitCode)"
        }
        Write-Info "Inspect the service log with: Get-EventLog -LogName Application -Source Puppet -Newest 20"
        return $false
    }

    $startMode = Get-PuppetServiceStartMode
    Write-Info "Service '$PUPPET_SERVICE_NAME' is Running with startup type $startMode"
    Write-Info "The agent will now apply its catalog every $PUPPET_RUNINTERVAL unattended"
    return $true
}

function Invoke-InitialPuppetRun {
    Write-Step "Running initial Puppet agent (certificate signing request)..."

    if ($DryRun) {
        Write-Info "[DRY RUN] Would run: puppet agent --test --waitforcert 0"
        return
    }

    if (-not (Test-Path $PUPPET_BIN)) {
        # Try common alternative paths
        $altPaths = @(
            "C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat",
            "C:\Program Files\Puppet Labs\Puppet\puppet\bin\puppet.bat"
        )
        $found = $false
        foreach ($altPath in $altPaths) {
            if (Test-Path $altPath) {
                $script:PUPPET_BIN = $altPath
                $found = $true
                break
            }
        }
        if (-not $found) {
            Write-Warn "puppet.bat not found at expected paths"
            Write-Info "You may need to run the initial puppet agent manually after installation completes"
            return
        }
    }

    Write-Info "Running: $PUPPET_BIN agent --test --waitforcert 0"

    # A native command's non-zero exit does not raise a PowerShell error, so the
    # previous catch block never fired and failures went unreported. Inspect
    # $LASTEXITCODE instead: 0 = no changes, 2 = changes applied, 1 = the run
    # could not proceed (usually an unsigned certificate), 4/6 = resource errors.
    $previousPreference = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        & $PUPPET_BIN agent --test --waitforcert 0
        $runExit = $LASTEXITCODE
    }
    finally {
        $ErrorActionPreference = $previousPreference
    }

    switch ($runExit) {
        0 { Write-Info "Initial Puppet run completed with no changes" }
        2 { Write-Info "Initial Puppet run applied changes" }
        1 { Write-Info "Certificate request submitted - waiting for it to be signed" }
        default { Write-Warn "Initial Puppet run finished with exit code $runExit" }
    }
}

# ============================================================================
# Main
# ============================================================================

function Main {
    Write-Banner

    # Validate configuration
    # Note: the sentinel is split so it is not itself replaced by the WebUI's
    # placeholder substitution (which rewrites every "{{OPENVOX_SERVER}}").
    $placeholder = "{{OPENVOX_SERVER" + "}}"
    if ([string]::IsNullOrWhiteSpace($OPENVOX_SERVER) -or $OPENVOX_SERVER -eq $placeholder) {
        Write-Err "OpenVox Server URL is not configured!"
        Write-Err "Please configure 'openvox_server_url' in your OpenVox WebUI settings."
        exit 1
    }

    # Confirm with user unless non-interactive
    if (-not $NonInteractive -and -not $DryRun) {
        Write-Host ""
        Write-Host "This script will:" -ForegroundColor White
        Write-Host "  1. Download the latest OpenVox Agent MSI" -ForegroundColor White
        Write-Host "  2. Install the agent silently" -ForegroundColor White
        Write-Host "  3. Configure puppet.conf with server: $OPENVOX_SERVER" -ForegroundColor White
        Write-Host "  4. Submit a certificate signing request" -ForegroundColor White
        Write-Host "  5. Register the Puppet agent service and set it to start automatically" -ForegroundColor White
        Write-Host ""
        $confirm = Read-Host "Continue? [Y/n]"
        if ($confirm -and $confirm.ToLower() -ne "y") {
            Write-Host "Aborted." -ForegroundColor Yellow
            exit 0
        }
    }

    # Execute steps
    $versionInfo = Get-LatestMsiUrl
    $msiPath = Get-MsiInstaller -VersionInfo $versionInfo
    Install-OpenvoxAgent -MsiPath $msiPath
    Set-PuppetConfig

    # Make sure the service exists before touching it, but keep it stopped for
    # the foreground run below - a running service holds the agent lock and the
    # certificate request would be skipped with "run already in progress".
    $serviceRegistered = Register-PuppetService -MsiPath $msiPath
    if ($serviceRegistered -and -not $DryRun) {
        Stop-PuppetServiceIfRunning -ServiceName $PUPPET_SERVICE_NAME
    }

    Invoke-InitialPuppetRun

    # Only now hand control to the service so it keeps running unattended.
    $serviceRunning = $false
    if ($serviceRegistered) {
        $serviceRunning = Enable-PuppetService
    }

    # Cleanup temp files
    if (-not $DryRun) {
        $tempDir = Join-Path $env:TEMP "openvox-bootstrap"
        if (Test-Path $tempDir) {
            Remove-Item -Path $tempDir -Recurse -Force -ErrorAction SilentlyContinue
        }
    }

    Write-Host ""
    if ($serviceRunning -or $DryRun) {
        Write-Host "============================================================" -ForegroundColor Green
        Write-Host "  Bootstrap Complete!" -ForegroundColor Green
        Write-Host "============================================================" -ForegroundColor Green
    }
    else {
        Write-Host "============================================================" -ForegroundColor Yellow
        Write-Host "  Bootstrap finished with warnings" -ForegroundColor Yellow
        Write-Host "============================================================" -ForegroundColor Yellow
        Write-Host ""
        Write-Host "  The agent is installed but its service is not running." -ForegroundColor Yellow
        Write-Host "  It will NOT check in unattended until the service starts." -ForegroundColor Yellow
        Write-Host "  Fix it with:  sc.exe config $PUPPET_SERVICE_NAME start= auto" -ForegroundColor Yellow
        Write-Host "                Start-Service $PUPPET_SERVICE_NAME" -ForegroundColor Yellow
    }
    Write-Host ""
    Write-Host "  Next step: Sign the node's certificate in OpenVox WebUI" -ForegroundColor White
    Write-Host "  Navigate to: CA Management > Pending Requests" -ForegroundColor White
    Write-Host ""
    Write-Host "  Service status:  Get-Service $PUPPET_SERVICE_NAME" -ForegroundColor White
    Write-Host "  Manual run:      & '$PUPPET_BIN' agent -t" -ForegroundColor White
    if ($RebootRequired) {
        Write-Host ""
        Write-Warn "A reboot is pending from the MSI installation."
    }
    Write-Host ""

    if (-not $serviceRunning -and -not $DryRun) {
        exit 1
    }
}

# Run main
Main
