#!/bin/bash
#
# OpenVox Agent Bootstrap Script
#
# This script is dynamically generated by OpenVox WebUI and:
#   - Detects the OS (RHEL/CentOS, Amazon Linux, Fedora, SLES, Debian/Ubuntu, etc.)
#   - Sets up the OpenVox/Puppet repository
#   - Installs the openvox-agent package
#   - Configures puppet.conf to point to the Puppet server
#
# Supported Operating Systems:
#   - RHEL/CentOS/Rocky/AlmaLinux/Oracle Linux 7, 8, 9
#   - RHEL FIPS-enabled systems
#   - Amazon Linux 2, 2023
#   - Fedora (current versions)
#   - SUSE Linux Enterprise Server (SLES) 12, 15
#   - openSUSE Leap
#   - Debian 10, 11, 12, 13
#   - Ubuntu 18.04, 20.04, 22.04, 24.04, 25.04
#   - Linux Mint (mapped to corresponding Ubuntu version)
#
# Usage:
#   curl -sSL https://your-openvox-webui/api/v1/bootstrap/script | sudo bash
#
# Or for non-interactive mode:
#   curl -sSL https://your-openvox-webui/api/v1/bootstrap/script | sudo bash -s -- --non-interactive
#
# Generated by OpenVox WebUI - https://github.com/ffquintella/openvox-webui
#

set -e

# Configuration (injected by OpenVox WebUI)
OPENVOX_SERVER="{{OPENVOX_SERVER}}"
REPO_BASE_URL="{{REPO_BASE_URL}}"
PACKAGE_NAME="{{PACKAGE_NAME}}"

# Default Vox Pupuli repository configuration
DEFAULT_YUM_REPO="https://yum.voxpupuli.org/openvox8"
DEFAULT_APT_REPO="https://apt.voxpupuli.org"  # APT uses release packages from apt.voxpupuli.org

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script options
INTERACTIVE=true
DRY_RUN=false

# OS detection variables
OS_ID=""
OS_VERSION_ID=""
OS_VERSION_CODENAME=""
OS_FAMILY=""
OS_MAJOR_VERSION=""
REPO_PATH=""

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

print_banner() {
    echo ""
    echo -e "${BLUE}╔═══════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║             OpenVox Agent Bootstrap Script                         ║${NC}"
    echo -e "${BLUE}╚═══════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "  OpenVox Server: ${OPENVOX_SERVER:-Not configured}"
    echo "  Package:        ${PACKAGE_NAME}"
    if [ -n "${REPO_BASE_URL}" ]; then
        echo "  Repository:     ${REPO_BASE_URL}"
    else
        echo "  Repository:     Vox Pupuli (default)"
    fi
    echo ""
}

detect_os() {
    log_step "Detecting operating system..."

    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS_ID="$ID"
        OS_VERSION_ID="$VERSION_ID"
        OS_VERSION_CODENAME="${VERSION_CODENAME:-}"

        case "$OS_ID" in
            rhel|centos|rocky|almalinux|ol)
                OS_FAMILY="redhat"
                OS_MAJOR_VERSION="${OS_VERSION_ID%%.*}"
                # Check if this is a FIPS-enabled RHEL system
                if [ "$OS_ID" = "rhel" ] && [ -f /proc/sys/crypto/fips_enabled ] && [ "$(cat /proc/sys/crypto/fips_enabled)" = "1" ]; then
                    REPO_PATH="redhatfips/${OS_MAJOR_VERSION}"
                else
                    REPO_PATH="el/${OS_MAJOR_VERSION}"
                fi
                ;;
            fedora)
                OS_FAMILY="redhat"
                OS_MAJOR_VERSION="${OS_VERSION_ID}"
                REPO_PATH="fedora/${OS_MAJOR_VERSION}"
                ;;
            amzn)
                OS_FAMILY="redhat"
                # Amazon Linux 2 reports VERSION_ID as "2", Amazon Linux 2023 as "2023"
                OS_MAJOR_VERSION="${OS_VERSION_ID}"
                REPO_PATH="amazon/${OS_MAJOR_VERSION}"
                ;;
            debian)
                OS_FAMILY="debian"
                OS_MAJOR_VERSION="${OS_VERSION_ID}"
                ;;
            ubuntu|linuxmint)
                OS_FAMILY="debian"
                OS_MAJOR_VERSION="${OS_VERSION_ID%%.*}"
                ;;
            sles)
                OS_FAMILY="suse"
                OS_MAJOR_VERSION="${OS_VERSION_ID%%.*}"
                REPO_PATH="sles/${OS_MAJOR_VERSION}"
                ;;
            opensuse-leap|opensuse-tumbleweed|opensuse)
                OS_FAMILY="suse"
                OS_MAJOR_VERSION="${OS_VERSION_ID%%.*}"
                # openSUSE Leap uses SLES packages
                REPO_PATH="sles/${OS_MAJOR_VERSION}"
                ;;
            *)
                log_error "Unsupported OS: $OS_ID"
                log_error "Supported operating systems:"
                log_error "  - RHEL/CentOS/Rocky/AlmaLinux/Oracle Linux 7, 8, 9"
                log_error "  - Amazon Linux 2, 2023"
                log_error "  - Fedora"
                log_error "  - SLES/openSUSE"
                log_error "  - Debian/Ubuntu"
                exit 1
                ;;
        esac

        log_info "Detected: ${PRETTY_NAME:-$OS_ID} (family: $OS_FAMILY)"
        if [ -n "$REPO_PATH" ]; then
            log_info "Repository path: $REPO_PATH"
        fi
    else
        log_error "Cannot detect OS - /etc/os-release not found"
        exit 1
    fi
}

setup_yum_repo() {
    log_step "Setting up YUM/DNF repository..."

    local repo_file="/etc/yum.repos.d/openvox.repo"
    local base_url=""

    if [ -n "${REPO_BASE_URL}" ]; then
        # Use custom repository URL
        base_url="${REPO_BASE_URL}/${REPO_PATH}"
        log_info "Using custom repository: $base_url"
    else
        # Use default Vox Pupuli OpenVox repository
        base_url="${DEFAULT_YUM_REPO}/${REPO_PATH}"
        log_info "Using Vox Pupuli repository: $base_url"
    fi

    cat > "$repo_file" << EOF
[openvox]
name=OpenVox Repository
baseurl=${base_url}/\$basearch
enabled=1
gpgcheck=0
EOF

    log_info "YUM repository configured: $repo_file"
}

setup_zypper_repo() {
    log_step "Setting up Zypper repository..."

    local base_url=""

    if [ -n "${REPO_BASE_URL}" ]; then
        # Use custom repository URL
        base_url="${REPO_BASE_URL}/${REPO_PATH}"
        log_info "Using custom repository: $base_url"
    else
        # Use default Vox Pupuli OpenVox repository
        base_url="${DEFAULT_YUM_REPO}/${REPO_PATH}"
        log_info "Using Vox Pupuli repository: $base_url"
    fi

    # Remove existing openvox repo if present
    zypper removerepo openvox 2>/dev/null || true

    # Add the repository
    zypper addrepo --no-gpgcheck --refresh "${base_url}/\$basearch" openvox || {
        log_error "Failed to add zypper repository"
        exit 1
    }

    # Refresh repositories
    zypper --gpg-auto-import-keys refresh || {
        log_warn "Repository refresh had warnings, continuing anyway"
    }

    log_info "Zypper repository configured"
}

setup_apt_repo() {
    log_step "Setting up APT repository..."

    # Install prerequisites
    log_info "Installing prerequisites..."
    apt-get update -qq
    apt-get install -y -qq curl gnupg ca-certificates lsb-release

    # Determine the distribution identifier for the Vox Pupuli repository
    # Vox Pupuli APT repo uses: debian10, debian11, debian12, debian13, ubuntu18.04, ubuntu20.04, etc.
    local dist_id=""
    case "$OS_ID" in
        debian)
            dist_id="debian${OS_VERSION_ID}"
            ;;
        ubuntu)
            dist_id="ubuntu${OS_VERSION_ID}"
            ;;
        linuxmint)
            # Linux Mint is based on Ubuntu, map to the appropriate Ubuntu version
            # Mint 20.x = Ubuntu 20.04, Mint 21.x = Ubuntu 22.04, Mint 22.x = Ubuntu 24.04
            local mint_major="${OS_VERSION_ID%%.*}"
            case "$mint_major" in
                20) dist_id="ubuntu20.04" ;;
                21) dist_id="ubuntu22.04" ;;
                22) dist_id="ubuntu24.04" ;;
                *) dist_id="ubuntu22.04" ;;  # Default fallback
            esac
            log_info "Linux Mint $OS_VERSION_ID mapped to $dist_id"
            ;;
        *)
            log_error "Unsupported Debian-based distribution: $OS_ID"
            exit 1
            ;;
    esac

    log_info "Distribution identifier: $dist_id"

    local base_url=""
    if [ -n "${REPO_BASE_URL}" ]; then
        # Use custom repository URL (assumes standard APT repo structure with codenames)
        local codename="${OS_VERSION_CODENAME}"
        if [ -z "$codename" ]; then
            codename=$(lsb_release -cs 2>/dev/null || echo "")
        fi
        base_url="${REPO_BASE_URL}"
        echo "deb ${base_url} ${codename} main" > /etc/apt/sources.list.d/openvox.list
        log_info "Using custom APT repository"
    else
        # Use default Vox Pupuli OpenVox repository
        # Try using release package first, fall back to manual configuration if needed
        local release_package="openvox8-release-${dist_id}.deb"
        local release_url="${DEFAULT_APT_REPO}/${release_package}"
        local use_manual_config=false

        log_info "Downloading Vox Pupuli release package: ${release_package}"

        # Download and install the release package
        local temp_deb="/tmp/${release_package}"
        if curl -sSL -o "${temp_deb}" "${release_url}" 2>/dev/null && dpkg -i "${temp_deb}" 2>/dev/null; then
            rm -f "${temp_deb}"
            log_info "Vox Pupuli repository configured via release package"

            # Test if the repository configuration works
            if ! apt-get update -qq 2>&1 | grep -q "apt.voxpupuli.org.*404"; then
                log_info "Repository configuration verified"
            else
                log_warn "Release package created invalid repository configuration, using manual configuration"
                use_manual_config=true
            fi
        else
            log_warn "Failed to install release package, using manual configuration"
            rm -f "${temp_deb}"
            use_manual_config=true
        fi

        # Manual configuration fallback
        if [ "$use_manual_config" = true ]; then
            log_info "Configuring Vox Pupuli APT repository manually"

            # Download and add GPG key
            curl -sSL "${DEFAULT_APT_REPO}/openvox-keyring.gpg" -o /usr/share/keyrings/openvox-keyring.gpg || {
                log_error "Failed to download GPG key"
                exit 1
            }

            # Create APT source configuration using DEB822 format (modern format)
            cat > /etc/apt/sources.list.d/openvox8.sources << EOF
Types: deb
URIs: ${DEFAULT_APT_REPO}
Suites: ${dist_id}
Components: openvox8
Signed-By: /usr/share/keyrings/openvox-keyring.gpg
EOF

            log_info "Manual APT repository configuration completed"
        fi
    fi

    # Update package lists
    apt-get update -qq
    log_info "APT repository configured"
}

install_agent() {
    log_step "Installing ${PACKAGE_NAME}..."

    case "$OS_FAMILY" in
        redhat)
            if command -v dnf &> /dev/null; then
                dnf install -y "$PACKAGE_NAME" || {
                    log_error "Failed to install package with dnf"
                    exit 1
                }
            else
                yum install -y "$PACKAGE_NAME" || {
                    log_error "Failed to install package with yum"
                    exit 1
                }
            fi
            ;;
        debian)
            apt-get install -y "$PACKAGE_NAME" || {
                log_error "Failed to install package with apt"
                exit 1
            }
            ;;
        suse)
            zypper install -y "$PACKAGE_NAME" || {
                log_error "Failed to install package with zypper"
                exit 1
            }
            ;;
    esac

    log_info "Package ${PACKAGE_NAME} installed successfully"
}

configure_puppet() {
    log_step "Configuring Puppet agent..."

    local puppet_conf="/etc/puppetlabs/puppet/puppet.conf"
    local puppet_conf_dir="/etc/puppetlabs/puppet"

    # Create directory if needed
    mkdir -p "$puppet_conf_dir"

    # Backup existing config if present
    if [ -f "$puppet_conf" ]; then
        log_info "Backing up existing puppet.conf"
        cp "$puppet_conf" "${puppet_conf}.backup.$(date +%Y%m%d%H%M%S)"
    fi

    # Configure puppet.conf
    cat > "$puppet_conf" << EOF
[main]
server = ${OPENVOX_SERVER}

[agent]
# Run puppet agent every 30 minutes
runinterval = 30m
EOF

    log_info "Puppet configured with server: ${OPENVOX_SERVER}"
}

enable_puppet_service() {
    log_step "Enabling Puppet agent service..."

    if command -v systemctl &> /dev/null; then
        systemctl enable puppet || log_warn "Could not enable puppet service"
        log_info "Puppet service enabled"
    else
        log_warn "systemctl not found, skipping service enable"
    fi
}

run_puppet_agent() {
    log_step "Running initial Puppet agent..."

    local puppet_bin="/opt/puppetlabs/bin/puppet"

    if [ ! -x "$puppet_bin" ]; then
        log_error "Puppet binary not found at $puppet_bin"
        exit 1
    fi

    # Run puppet agent to generate certificate request
    # --waitforcert will wait up to 60 seconds for cert to be signed
    log_info "Submitting certificate signing request..."
    $puppet_bin agent --test --waitforcert 60 || true

    log_info "Puppet agent run completed"
}

print_next_steps() {
    echo ""
    echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}                    Bootstrap Complete!                             ${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
    echo ""
    echo "The Puppet agent has been installed and configured."
    echo ""
    echo "Next steps:"
    echo "  1. Sign the certificate on the Puppet server or via OpenVox WebUI"
    echo "     - On Puppet server: puppetserver ca sign --certname $(hostname -f)"
    echo "     - Or use the OpenVox WebUI CA Management page"
    echo ""
    echo "  2. After signing, run 'puppet agent -t' to apply configuration"
    echo ""
    echo "Useful commands:"
    echo "  - Check certificate status:    puppet ssl verify"
    echo "  - Run puppet manually:         puppet agent -t"
    echo "  - Start puppet daemon:         systemctl start puppet"
    echo "  - Check puppet service status: systemctl status puppet"
    echo ""
}

show_help() {
    echo "OpenVox Agent Bootstrap Script"
    echo ""
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --non-interactive    Run without prompts (for automated deployments)"
    echo "  --dry-run           Show what would be done without making changes"
    echo "  --help, -h          Show this help message"
    echo ""
    echo "Environment Variables:"
    echo "  OPENVOX_SERVER      Override the OpenVox server URL"
    echo "  PACKAGE_NAME        Override the package to install"
    echo ""
    echo "Supported Operating Systems:"
    echo "  - RHEL/CentOS/Rocky/AlmaLinux/Oracle Linux 7, 8, 9"
    echo "  - RHEL FIPS-enabled systems"
    echo "  - Amazon Linux 2, 2023"
    echo "  - Fedora (current versions)"
    echo "  - SUSE Linux Enterprise Server (SLES) 12, 15"
    echo "  - openSUSE Leap"
    echo "  - Debian 10, 11, 12, 13"
    echo "  - Ubuntu 18.04, 20.04, 22.04, 24.04, 25.04"
    echo "  - Linux Mint (mapped to Ubuntu)"
    echo ""
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --non-interactive)
            INTERACTIVE=false
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --help|-h)
            show_help
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            show_help
            exit 1
            ;;
    esac
done

# Allow environment variable overrides
if [ -n "${OPENVOX_SERVER_OVERRIDE:-}" ]; then
    OPENVOX_SERVER="$OPENVOX_SERVER_OVERRIDE"
fi
if [ -n "${PACKAGE_NAME_OVERRIDE:-}" ]; then
    PACKAGE_NAME="$PACKAGE_NAME_OVERRIDE"
fi

# Main execution
main() {
    print_banner

    # Check if running as root
    if [ "$(id -u)" -ne 0 ]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi

    # Check if OpenVox server is configured
    # Note: The placeholder check uses a split string to avoid being replaced by the template engine
    local placeholder="{{OPENVOX_SERVER"
    placeholder="${placeholder}}}"
    if [ "${OPENVOX_SERVER}" = "${placeholder}" ] || [ -z "${OPENVOX_SERVER}" ]; then
        log_error "OpenVox server URL is not configured!"
        log_error "Please configure the OpenVox Server URL in OpenVox WebUI settings."
        exit 1
    fi

    if [ "$DRY_RUN" = true ]; then
        log_warn "DRY RUN MODE - No changes will be made"
        echo ""
        detect_os
        echo ""
        echo "Would perform the following steps:"
        echo "  1. Setup package repository for $OS_FAMILY ($REPO_PATH)"
        echo "  2. Install ${PACKAGE_NAME}"
        echo "  3. Configure puppet.conf with server: ${OPENVOX_SERVER}"
        echo "  4. Enable puppet service"
        echo "  5. Run puppet agent to submit certificate request"
        exit 0
    fi

    detect_os

    case "$OS_FAMILY" in
        redhat)
            setup_yum_repo
            ;;
        debian)
            setup_apt_repo
            ;;
        suse)
            setup_zypper_repo
            ;;
    esac

    install_agent
    configure_puppet
    enable_puppet_service
    run_puppet_agent
    print_next_steps
}

main "$@"
