#!/bin/bash
# Script to fix Code Deploy configuration paths on the server

set -e

echo "=== Code Deploy Configuration Fix Script ==="
echo ""

# Check current config
echo "1. Current config.yaml Code Deploy section:"
if [ -f /etc/openvox-webui/config.yaml ]; then
    grep -A 5 "^code_deploy:" /etc/openvox-webui/config.yaml || echo "  (Code Deploy section not found)"
else
    echo "  Config file does not exist!"
fi
echo ""

# Stop the service
echo "2. Stopping openvox-webui service..."
systemctl stop openvox-webui
echo "  Service stopped."
echo ""

# Backup current config
echo "3. Backing up current config..."
if [ -f /etc/openvox-webui/config.yaml ]; then
    cp /etc/openvox-webui/config.yaml /etc/openvox-webui/config.yaml.backup.$(date +%Y%m%d-%H%M%S)
    echo "  Backup created."
else
    echo "  No config to backup."
fi
echo ""

# Remove the config file to force Puppet to regenerate it
echo "4. Removing config file to force regeneration..."
rm -f /etc/openvox-webui/config.yaml
echo "  Config file removed."
echo ""

# Run puppet agent
echo "5. Running puppet agent to regenerate config..."
puppet agent -t || true
echo ""

# Check if config was regenerated
if [ -f /etc/openvox-webui/config.yaml ]; then
    echo "6. New config.yaml Code Deploy section:"
    grep -A 5 "^code_deploy:" /etc/openvox-webui/config.yaml || echo "  (Code Deploy section not found)"
    echo ""

    # Check if the path is correct
    if grep -q 'repos_base_dir: "/var/lib/openvox-webui/code-deploy/repos"' /etc/openvox-webui/config.yaml; then
        echo "✓ Config has been updated with correct paths!"
    else
        echo "✗ Config still has incorrect paths!"
        echo ""
        echo "Current repos_base_dir:"
        grep "repos_base_dir:" /etc/openvox-webui/config.yaml
    fi
else
    echo "✗ Config file was not regenerated by Puppet!"
fi
echo ""

# Create directories
echo "7. Creating Code Deploy directories..."
mkdir -p /var/lib/openvox-webui/code-deploy/repos
chown openvox-webui:openvox-webui /var/lib/openvox-webui/code-deploy/repos
chmod 0750 /var/lib/openvox-webui/code-deploy/repos
echo "  Directories created."
echo ""

# Start the service
echo "8. Starting openvox-webui service..."
systemctl start openvox-webui
echo "  Service started."
echo ""

echo "=== Fix Complete ==="
echo ""
echo "To verify, check the service status:"
echo "  systemctl status openvox-webui"
echo ""
echo "And check the logs:"
echo "  journalctl -u openvox-webui -f"
